export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
